[package]
name = "integration_tests"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
airplay2 = { path = "../" }
tokio = { version = "1.43", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nix = { version = "0.29", features = ["process", "signal"] }
chrono = "0.4"
bytes = "1.11.1"
tempfile = "3.10"
walkdir = "2.5.0"
rand = "0.8"
